CREATE TABLE limits (
    id BIGSERIAL PRIMARY KEY,
    client_id INT NOT NULL UNIQUE,
    daily_limit NUMERIC(10, 2) NOT NULL DEFAULT 10000,
    remaining_limit NUMERIC(10, 2) NOT NULL DEFAULT 10000,
    last_reset TIMESTAMP NOT NULL DEFAULT CURRENT_DATE
);